#!/bin/bash

set -eE

src_dir=~/src
release=24.3
build_dir=$src_dir/emacs-${release}
bundle_file=emacs-${release}.tar.xz
sig_file=${bundle_file}.sig

file_uri=http://ftp.gnu.org/gnu/emacs/$bundle_file

# always download signature from gnu.org
sig_uri=http://ftp.gnu.org/gnu/emacs/$sig_file

################

mkdir -p ~/Downloads
cd ~/Downloads

curl -LOC - $sig_uri

if [ ! -f ~/Downloads/$bundle_file ] ; then
    curl -LOC - $file_uri
fi

# gpg --keyserver pgpkeys.mit.edu --recv-key A0B0F199
if ! gpg --verify ~/Downloads/$sig_file ~/Downloads/$bundle_file ; then
    echo "ERROR: file doesn't match signature" >&2
    ls -l ~/Downloads/$bundle_file
    exit 1
fi

cd ~/src
# rm -rf $build_dir
# tar Jxvf ~/Downloads/$bundle_file
cd $build_dir

################
# dependencies

if [ -f /etc/os-release ] ; then
    file=/etc/os-release
elif [ -f /etc/system-release ] ; then
    file=/etc/system-release
else
    echo "ERROR: cannot determine os type. install dependencies manually" >&2
    exit 1
fi

if grep -i -q debian $file ; then
    sudo apt-get install build-essential
    sudo apt-get build-dep emacs24
elif grep -i -q 'Red Hat' $file ; then
    sudo yum install gtk2 gtk2-devel libXpm-devel giflib-devel libtiff-devel libjpeg libjpeg-devel ncurses ncurses-devel
else
    echo "ERROR: cannot determine os type. install dependencies manually" >&2
    exit 1
fi

################

./configure
make
sudo make install
sudo alternatives --install /usr/bin/emacs emacs /usr/local/bin/emacs 20000
